require.config({
    paths:{
        'jquery':'./libs/jquery-2.1.1',
        'swiper':'./libs/swiper-4.1.6.min',
        'handlebars':'./libs/handlebars',
        'scroll':'./libs/bscroll.min',
        'index':'./app/index'
    }
})
require(['index'])